import { ChangeDetectionStrategy, Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatLineModule } from '@angular/material/core';
import { MatDividerModule } from '@angular/material/divider';
import { MatListModule } from '@angular/material/list';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'ngrx-traits-examples',
  template: `
    <mat-card>
      <mat-card-header>
        <mat-card-title>Traits examples</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <mat-list>
          <mat-list-item [routerLink]="'infinite-scroll-dropdown'">
            <div matListItemTitle><b>Infinite Scroll Dropdown</b></div>
            <div matListItemLine>
              Example of withEntitiesRemoteScrollPagination used to create a
              dropdown with infinite scroll
            </div>
          </mat-list-item>
          <mat-list-item [routerLink]="'infinite-scroll-list'">
            <div matListItemTitle><b>Infinite Scroll List</b></div>
            <div matListItemLine>
              Example of withEntitiesRemoteScrollPagination used to create a
              list tha is paginated for desktop mode and uses an infinite scroll
              in mobile mode
            </div>
          </mat-list-item>
          <mat-divider></mat-divider>
          <mat-list-item [routerLink]="'product-list-paginated'">
            <div matListItemTitle><b>Paginated List</b></div>
            <div matListItemLine>
              Example using store features to load a product list with remote
              filtering and detail view
            </div>
          </mat-list-item>
          <mat-list-item [routerLink]="'product-list-ssr'">
            <div matListItemTitle><b>SSR Product List</b></div>
            <div matListItemLine>
              Example with SSR state hydration using withServerStateTransfer.
              URL params pre-hydrate from server
            </div>
          </mat-list-item>
          <mat-list-item [routerLink]="'products-shop'">
            <div matListItemTitle>
              <b
                >Complex example using two collections and most of the store
                features</b
              >
            </div>
            <div matListItemLine>
              Example using two collection in the store, one for products and
              one for a product basket, you can find here examples of withCalls,
              remote pagination,sorting and filtering , local sorting,
              pagination, single and multi selection and more
            </div>
          </mat-list-item>
          <mat-list-item [routerLink]="'register-user'">
            <div matListItemTitle><b>Register User Form</b></div>
            <div matListItemLine>
              Example using withCalls + Angular Signal Forms for form submission
              with async error handling
            </div>
          </mat-list-item>
          <mat-list-item [routerLink]="'product-link'">
            <div matListItemTitle>
              <b>Product Search and Edit (withLink)</b>
            </div>
            <div matListItemLine>
              Example using withLink to connect the store to signal forms and a
              model(): a validated filter form, a genre picker synced with
              syncWith, and an edit panel that writes valid changes back to the
              list
            </div>
          </mat-list-item>
          <mat-list-item [routerLink]="'product-resource'">
            <div matListItemTitle>
              <b>Product List and Detail (Resource API)</b>
            </div>
            <div matListItemLine>
              Example using the Angular Resource views generated by
              withEntitiesLoadingCall and withCalls: a remotely filtered list
              where clicking a row loads the product detail
            </div>
          </mat-list-item>
          <mat-list-item [routerLink]="'order-list'">
            <div matListItemTitle><b>Drill-down List</b></div>
            <div matListItemLine>
              Example using store features to load a order list where you can
              expand each order to see the order details, this uses
              withEntitiesCalls to allow you to load the order details
            </div>
          </mat-list-item>
        </mat-list>
      </mat-card-content>
    </mat-card>
  `,
  styles: `
    /* let items grow with their text instead of material's fixed heights */
    :host {
      --mat-list-list-item-one-line-container-height: auto;
      --mat-list-list-item-two-line-container-height: auto;
      --mat-list-list-item-three-line-container-height: auto;
    }
    .mat-mdc-list-item {
      padding-block: 8px;
    }
    .mat-mdc-list-item .mat-mdc-list-item-title.mdc-list-item__primary-text,
    .mat-mdc-list-item .mat-mdc-list-item-line.mdc-list-item__secondary-text {
      white-space: normal;
      -webkit-line-clamp: unset;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [
    MatCardModule,
    MatListModule,
    RouterLink,
    MatLineModule,
    MatDividerModule,
  ],
})
export class SignalExamplesComponent {}
