import {
  createTraitFactory,
  TraitActionsFactoryConfig,
  TraitInitialStateFactoryConfig,
  TraitSelectorsFactoryConfig,
  TraitStateMutatorsFactoryConfig,
} from 'ngrx-traits';
import { createCrudTraitActions } from '../crud/crud.trait.actions';
import { createCrudTraitSelectors } from '../crud/crud.trait.selectors';
import {
  createCrudInitialState,
  createCrudTraitReducer,
} from '../crud/crud.trait.reducer';
import { SortActions, SortKeyedConfig } from '../sort/sort.model';
import {
  CrudActions,
  CrudConfig,
  CrudKeyedConfig,
  crudTraitKey,
} from './crud.model';
import { FilterActions, FilterKeyedConfig } from '../filter/filter.model';
import {
  LoadEntitiesActions,
  LoadEntitiesKeyedConfig,
  LoadEntitiesSelectors,
  loadEntitiesTraitKey,
} from '../load-entities/load-entities.model';
import {
  PaginationActions,
  PaginationKeyedConfig,
} from '../pagination/pagination.model';
import { createCrudTraitMutators } from './crud.trait.mutators';

/**
 * Generates ngrx code to add, remove update, upsert entities on a list, it also
 * tracks the changes made, helpful for implementing batch updates. The `storeChanges` (false by default),
 * will store for add and update the changed entity props in the property `entityChanges` of the `Change` object.
 * @param config
 * @param config.storeChanges - Will store the changes made, default fals
 *
 * @example
 * // The following trait config
 *
 * export interface TestState
 * extends EntityAndStatusState<Todo>, CrudState<Todo>{}
 *
 *    const traits = createEntityFeatureFactory(
 *      addLoadEntities<Todo>(),
 *      addCrudEntities<Todo>()
 *    )({
 *      actionsGroupKey: '[Todos]',
 *      featureSelector: createFeatureSelector<TestState>>(
 *        'todos',
 *      ),
 *    });
 * // will generate  the following actions and selectors, plus the ones generated by other traits
 * traits.actions.add(entity1,entity2...)
 * traits.actions.update({id: id1, changes:{prop1}},{id: id2, changes:{prop2}} ...)
 * traits.actions.upsert(entity1,entity2...)
 * traits.actions.removeAll()
 * traits.actions.clearChanges()
 *
 * traits.actions.selectChanges({id})
 * traits.selectors.selectAllChanges()
 * traits.selectors.selectEntitySelected()
 * traits.selectors.selectFilteredChanges()
 * traits.selectors.selectAllFilteredChanges()
 */
export function addCrudEntities<Entity>({
  storeChanges = false,
}: CrudConfig = {}) {
  return createTraitFactory({
    key: crudTraitKey,
    depends: [loadEntitiesTraitKey],
    config: { storeChanges } as CrudConfig,
    actions: ({ actionsGroupKey }: TraitActionsFactoryConfig) =>
      createCrudTraitActions<Entity>(actionsGroupKey),
    selectors: ({ previousSelectors }: TraitSelectorsFactoryConfig) =>
      createCrudTraitSelectors<Entity>(
        previousSelectors as LoadEntitiesSelectors<Entity>
      ),
    mutators: ({ allConfigs }: TraitStateMutatorsFactoryConfig) =>
      createCrudTraitMutators<Entity>(
        allConfigs as CrudKeyedConfig & LoadEntitiesKeyedConfig<Entity>
      ),
    initialState: ({ previousInitialState }: TraitInitialStateFactoryConfig) =>
      createCrudInitialState<Entity>(previousInitialState),
    reducer: ({ initialState, allActions, allMutators, allConfigs }) =>
      createCrudTraitReducer(
        initialState,
        allActions as CrudActions<Entity> &
          LoadEntitiesActions<Entity> &
          SortActions<Entity> &
          FilterActions<any> &
          PaginationActions,
        allMutators,
        allConfigs as CrudKeyedConfig &
          FilterKeyedConfig<Entity, unknown> &
          LoadEntitiesKeyedConfig<Entity> &
          SortKeyedConfig<Entity> &
          PaginationKeyedConfig
      ),
  });
}
