import { createSelectEntitiesTraitActions } from './select-entities.trait.actions';
import { SortEntitiesActions, SortEntitiesKeyedConfig } from '../sort-entities';
import { createSelectEntitiesTraitSelectors } from './select-entities.trait.selectors';
import {
  SelectEntitiesSelectors,
  SelectEntitiesActions,
} from './select-entities.model';
import {
  EntitiesPaginationActions,
  EntitiesPaginationKeyedConfig,
} from '../entities-pagination/entities-pagination.model';
import {
  LoadEntitiesActions,
  LoadEntitiesKeyedConfig,
  LoadEntitiesSelectors,
  loadEntitiesTraitKey,
} from '../load-entities/load-entities.model';
import { createTraitFactory } from 'ngrx-traits';
import { CrudEntitiesActions } from '../crud-entities/crud-entities.model';
import {
  createSelectEntitiesInitialState,
  createSelectEntitiesTraitReducer,
} from './select-entities.trait.reducer';
import { createSelectEntitiesTraitMutators } from './select-entities.trait.mutators';
import { FilterEntitiesActions } from '../filter-entities';
import {
  TraitActionsFactoryConfig,
  TraitInitialStateFactoryConfig,
  TraitSelectorsFactoryConfig,
  TraitStateMutatorsFactoryConfig,
} from 'ngrx-traits';

/**
 * Generates ngrx code to add multi selection to a list
 *
 * @example
 * // The following trait config
 *
 * export interface TestState
 * extends EntityAndStatusState<Todo>,MultipleSelectionState{}
 *
 *    const traits = createEntityFeatureFactory(
 *      addLoadEntitiesTrait<Todo>(),
 *      addSelectEntities<Todo>()
 *    )({
 *      actionsGroupKey: '[Todos]',
 *      featureSelector: createFeatureSelector<TestState>>(
 *        'todos',
 *      ),
 *    });
 * // will generate  the following actions and selectors, plus the ones generated by other traits
 * traits.actions.multiSelect({id})
 * traits.actions.multiDeselect({id})
 * traits.actions.multiToggleSelect({id})
 * traits.actions.toggleSelectAll()
 * traits.actions.multiClearSelection()
 *
 * traits.selectors.selectIdSelected()
 * traits.selectors.selectEntitySelected()
 */
export function addSelectEntitiesTrait<Entity>() {
  return createTraitFactory({
    key: 'SelectEntities',
    depends: [loadEntitiesTraitKey],
    actions: ({ actionsGroupKey, entitiesName }: TraitActionsFactoryConfig) =>
      createSelectEntitiesTraitActions(actionsGroupKey, entitiesName),
    selectors: ({ previousSelectors }: TraitSelectorsFactoryConfig) =>
      createSelectEntitiesTraitSelectors<Entity>(
        previousSelectors as LoadEntitiesSelectors<Entity>
      ),
    initialState: ({ previousInitialState }: TraitInitialStateFactoryConfig) =>
      createSelectEntitiesInitialState<Entity>(previousInitialState),
    mutators: ({ allSelectors }: TraitStateMutatorsFactoryConfig) =>
      createSelectEntitiesTraitMutators<Entity>(
        allSelectors as SelectEntitiesSelectors<Entity>
      ),
    reducer: ({ initialState, allActions, allMutators, allConfigs }) =>
      createSelectEntitiesTraitReducer(
        initialState,
        allActions as SelectEntitiesActions &
          CrudEntitiesActions<Entity> &
          SortEntitiesActions<Entity> &
          LoadEntitiesActions<Entity> &
          FilterEntitiesActions<any> &
          EntitiesPaginationActions,
        allMutators,
        allConfigs as LoadEntitiesKeyedConfig<Entity> &
          EntitiesPaginationKeyedConfig &
          SortEntitiesKeyedConfig<Entity>
      ),
  });
}
