import { SignalStoreFeatureResult } from '@ngrx/signals';

import { CallResource } from '../call-resource/call-resource.model';
import { NamedSetEntitiesResult } from '../with-entities-pagination/with-entities-local-pagination.model';

/**
 * The `entitiesResource()` method generated by withEntitiesLoadingCall without
 * a collection: returns a resource view of the entities and their loading
 * call, see `CallResource`.
 */
export type EntitiesResourceMethods<Entity, Error = unknown> = {
  entitiesResource: () => CallResource<Entity[], Error>;
};

/**
 * The `<collection>EntitiesResource()` method generated by
 * withEntitiesLoadingCall for a named collection.
 */
export type NamedEntitiesResourceMethods<
  Collection extends string,
  Entity,
  Error = unknown,
> = {
  [K in Collection as `${K}EntitiesResource`]: () => CallResource<
    Entity[],
    Error
  >;
};

/**
 * The `entitiesResource()` or `<collection>EntitiesResource()` method depending
 * on the collection.
 */
export type EntitiesResourceMethodsFor<
  Collection extends string,
  Entity,
  Error = unknown,
> = Collection extends ''
  ? EntitiesResourceMethods<Entity, Error>
  : NamedEntitiesResourceMethods<Collection, Entity, Error>;

/**
 * The key an entities pagination feature generates to store a page result.
 */
type SetEntitiesPagedResultKey<Collection extends string> =
  Collection extends ''
    ? 'setEntitiesPagedResult'
    : `set${Capitalize<Collection>}EntitiesPagedResult`;

/**
 * The result fetchEntities returns, when the store has an entities pagination
 * feature it is whatever its set[Collection]EntitiesPagedResult accepts, which
 * varies per pagination feature, e.g. { entities, total } for
 * withEntitiesRemotePagination, otherwise the plain entities result.
 */
export type FetchEntitiesResult<
  Input extends SignalStoreFeatureResult,
  Collection extends string,
  Entity,
> =
  Input['methods'] extends NamedSetEntitiesResult<Collection, infer ResultParam>
    ? ResultParam
    : Entity[] | { entities: Entity[] };

/**
 * Adds an unreachable member to the result type, its key explains why the
 * result has that shape, so a wrong result reports
 *
 * Type 'Observable<Product[]>' is not assignable to type
 * 'Observable<PagedFetchEntitiesResult<{ entities: Product[]; total: number },
 * "the store has an entities pagination feature, fetchEntities must return the
 * result setEntitiesPagedResult accepts">>'
 *
 * instead of only naming the properties that are missing.
 */
export type PagedFetchEntitiesResult<ResultParam, Explanation extends string> =
  | ResultParam
  | { [K in Explanation]: never };

/**
 * Same as FetchEntitiesResult, but explaining where the shape comes from when
 * the store has an entities pagination feature. Only for the value fetchEntities
 * returns, results handed back to the user, like the onSuccess param, use
 * FetchEntitiesResult so they don't have to narrow the explanation away.
 */
export type ExpectedFetchEntitiesResult<
  Input extends SignalStoreFeatureResult,
  Collection extends string,
  Entity,
> =
  Input['methods'] extends NamedSetEntitiesResult<Collection, infer ResultParam>
    ? PagedFetchEntitiesResult<
        ResultParam,
        `the store has an entities pagination feature, fetchEntities must return the result ${SetEntitiesPagedResultKey<Collection>} accepts`
      >
    : Entity[] | { entities: Entity[] };

/**
 * The message key FetchEntitiesResultCheck requires when the store has an
 * entities pagination feature whose set[Collection]EntitiesPagedResult does not
 * accept the fetchEntities Result, never otherwise.
 */
type PagedResultMismatch<
  Input extends SignalStoreFeatureResult,
  Collection extends string,
  Result,
> =
  Input['methods'] extends NamedSetEntitiesResult<Collection, infer ResultParam>
    ? [Result] extends [ResultParam]
      ? never
      : `the store has an entities pagination feature, fetchEntities must return the result ${SetEntitiesPagedResultKey<Collection>} accepts`
    : never;

/**
 * Checks the fetchEntities Result against the entities pagination feature, if
 * the store has one, intersected with the Result a wrong one reports
 *
 * Property '"the store has an entities pagination feature, fetchEntities must
 * return the result setProductEntitiesPagedResult accepts"' is missing in type
 * 'Product[]'
 *
 * Unlike ExpectedFetchEntitiesResult it is a mapped type over the mismatch
 * key, when the store type is generic (a custom store feature with a generic
 * Collection) the key can not be resolved, the mapped type stays generic and
 * typescript accepts any result for it, so it only fails for known stores.
 */
export type FetchEntitiesResultCheck<
  Input extends SignalStoreFeatureResult,
  Collection extends string,
  Result,
> = {
  [K in PagedResultMismatch<Input, Collection, Result>]: unknown;
};

/**
 * Fails for a literal collection with a readable message, so the generic
 * Collection overload of withEntitiesLoadingCall never takes a call the literal
 * collection overload rejects, e.g. for an onSuccess param narrower than the
 * FetchEntitiesResult, which it types differently.
 *
 * Same trick as FetchEntitiesResultCheck, a mapped type over a key that
 * typescript can not resolve while Collection is a generic param, so it accepts
 * any entity config for it. The infer is what keeps the key lenient, a plain
 * string extends Collection conditional is rejected.
 */
export type GenericCollectionCheck<Collection extends string> = {
  [K in [Collection] extends [infer C]
    ? [string] extends [C]
      ? never
      : 'a literal collection is not a generic Collection param, check the literal collection overload errors'
    : never]: unknown;
};
