import {
  computed,
  effect,
  isSignal,
  linkedSignal,
  Signal,
  untracked,
  WritableSignal,
} from '@angular/core';
import { SIGNAL } from '@angular/core/primitives/signals';
import {
  patchState,
  SignalStoreFeature,
  signalStoreFeature,
  SignalStoreFeatureResult,
  withMethods,
} from '@ngrx/signals';

import { capitalize } from '../util';
import { withFeatureFactory } from '../with-feature-factory/with-feature-factory';
import { StoreSource } from '../with-feature-factory/with-feature-factory.model';

type LinkCommonOptions<T> = {
  /**
   * Gates which writes reach the store. When provided, the returned signal
   * becomes a `linkedSignal` buffer over the source: writes are kept locally
   * and only pushed to the store when `updateWhen(value)` returns true.
   *
   * It runs inside an effect, so it is reactive: a value held back while it
   * returned false is pushed as soon as its dependencies make it true
   * (e.g. a form becoming valid).
   *
   * Requires an injection context, since an effect is created.
   */
  updateWhen?: (value: T) => boolean;
};

/**
 * Options of the generated `link<Name>()` method.
 *
 * `syncWith` is mutually exclusive with `readFrom`/`writeTo`: use `syncWith`
 * when the external signal already matches the store type, or the
 * `readFrom` + `writeTo` pair when each direction needs its own mapping.
 */
export type LinkOptions<T = any> =
  | (LinkCommonOptions<T> & {
      /**
       * External signal kept in sync with the store both ways: writing it
       * updates the store, and store changes are written back to it.
       * Requires a WritableSignal (e.g. `model()`).
       */
      syncWith: WritableSignal<T>;
      readFrom?: never;
      writeTo?: never;
      /**
       * Which value wins on link.
       * - 'external' (default): the signal's current value is pushed to the store.
       * - 'store': the store value is written to the signal.
       */
      initialValue?: 'store' | 'external';
    })
  | (LinkCommonOptions<T> & {
      /**
       * External signal the store only reads from: its value is pushed to the
       * store, and store changes are never written back. Accepts any signal,
       * including a writable one whose writes you drive yourself
       * (e.g. a `model()` only written on a button click), or a `computed`
       * that maps an external model to the store type.
       *
       * Also accepts a function that receives the previous linked value (the
       * store value, or the buffer when `updateWhen` is used) so a partial
       * external signal can be merged into it, e.g.
       * `(prev) => ({ ...prev, search: this.search() })`. The signals it
       * reads are tracked; the previous value is not, so store changes alone
       * do not re-run it.
       */
      readFrom?: Signal<T> | ((prev: T) => T);
      /**
       * Where store changes are pushed: a WritableSignal that is set, or a
       * function called with the new value — use it to map back to an
       * external model's type, or to emit an output. Only changes after link
       * are pushed, the value at link time is not.
       *
       * Combine with `readFrom` for a two-way sync with a mapping in each
       * direction. Cannot be combined with `syncWith`.
       */
      writeTo?: WritableSignal<T> | ((value: T) => void);
      syncWith?: never;
      initialValue?: never;
    });

/** The `link<Name>()` method generated by `withLink`. */
export type LinkMethod<T> = (options?: LinkOptions<T>) => WritableSignal<T>;

export type LinkSourceOptions<
  Input extends SignalStoreFeatureResult,
  K extends keyof Input['state'],
> = {
  update?: (
    value: Input['state'][NoInfer<K>],
    store: StoreSource<Input>,
  ) => void;
  /**
   * Equality used to suppress redundant syncs in both directions.
   * Defaults to Object.is. Provide a structural comparison when the source
   * produces fresh object/array references (e.g. entity selections).
   */
  equal?: (
    a: Input['state'][NoInfer<K>],
    b: Input['state'][NoInfer<K>],
  ) => boolean;
  computation?: never;
};

export type LinkComputedOptions<Input extends SignalStoreFeatureResult, T> = {
  computation: (store: StoreSource<Input>) => T;
  update: (value: T, store: StoreSource<Input>) => void;
  /**
   * Equality used to suppress redundant syncs in both directions.
   * Defaults to Object.is. Provide a structural comparison when the source
   * produces fresh object/array references (e.g. entity selections).
   */
  equal?: (a: NoInfer<T>, b: NoInfer<T>) => boolean;
};

/**
 * Generates a `link<Name>()` method that connects store state to component
 * signals (inputs, models, signal forms).
 *
 * The first argument names the generated method and doubles as the state key
 * to link to, unless `computation` is provided in the options — then it is
 * just a name and the value is derived from the store.
 *
 * The method always returns a WritableSignal that is a live view of the store:
 * reading it reads the source, writing it calls `update` (or `patchState` by
 * default). It takes an options object that can also connect an external
 * signal, in one of three ways:
 * - `syncWith`: two-way, requires a WritableSignal (e.g. `model()`).
 * - `readFrom`: one-way external → store, accepts any signal — including a
 *   writable one you only write yourself (e.g. a `model()` set by a button) —
 *   or a function receiving the previous value, to merge a partial signal in.
 * - `writeTo`: one-way store → external, a WritableSignal that is set or a
 *   function called with each committed change (e.g. an `output` emit).
 *
 * `readFrom` and `writeTo` combine into a two-way sync with a mapping in each
 * direction (e.g. a `model()` whose type differs from the store's); `syncWith`
 * is mutually exclusive with both, and `initialValue` only applies to it.
 *
 * Both sync directions are guarded by `equal` (default `Object.is`), so writes
 * only happen when the value actually changed — this prevents echo loops when
 * `update` transforms the value.
 *
 * `syncWith`, `readFrom`, `writeTo` and `updateWhen` each require an injection context
 * (field initializer or constructor), because effects are created to keep
 * things in sync. The plain no-arg form has no such requirement.
 *
 * @param name - State key to link to, or a custom name when `computation` is used
 * @param options.computation - Derive the linked value from the store
 * @param options.update - How writes reach the store; defaults to
 *   `patchState(store, { [name]: value })`, required with `computation`
 * @param options.equal - Equality guard for both sync directions
 *
 * @example
 * // State key - generates linkFilter(), writes patch state
 * const Store = signalStore(
 *   withState({ filter: { search: '' } }),
 *   withLink('filter'),
 * );
 * // in a component:
 * // filterForm = form(this.store.linkFilter());
 *
 * @example
 * // State key with custom update
 * withLink('productEntitiesFilter', {
 *   update: (value, store) => store.filterProductEntities({ filter: value }),
 * });
 *
 * @example
 * // Custom name with computation + update, synced two-way with a model() input
 * withLink('selectedGenreIds', {
 *   computation: (store) => store.genreIdsSelected(),
 *   update: (value, store) =>
 *     store.selectGenreEntities({ ids: value, clearSelectionBeforeSelect: true }),
 *   equal: (a, b) => a.length === b.length && a.every((v, i) => v === b[i]),
 * });
 * // in a component:
 * // value = model<string[]>([]);
 * // valueField = form(this.store.linkSelectedGenreIds({ syncWith: this.value }));
 *
 * @example
 * // One way: the store reads the model, writes to it stay local until the
 * // button pushes them
 * // draft = model<string>('');
 * // linked = this.store.linkFilter({ readFrom: this.draft });
 *
 * @example
 * // Merge a partial signal into the previous value: only search is external,
 * // other filter keys are left as they are
 * // search = input<string>(''); // store state is { search: string; category: string }
 * // linked = this.store.linkFilter({
 * //   readFrom: (prev) => ({ ...prev, search: this.search() }),
 * // });
 *
 * @example
 * // Two-way with a model of a different type: map in with a computed,
 * // map back out with a function
 * // search = model<string>(''); // store state is { search: string }
 * // linked = this.store.linkFilter({
 * //   readFrom: computed(() => ({ search: this.search() })),
 * //   writeTo: (value) => this.search.set(value.search),
 * // });
 *
 * @example
 * // Emit committed changes as an output
 * // filterChange = output<{ search: string }>();
 * // linked = this.store.linkFilter({
 * //   writeTo: (value) => this.filterChange.emit(value),
 * // });
 *
 * @example
 * // Buffered writes: only valid form data reaches the store
 * // filterForm = form(this.formData, (value) => required(value.search));
 * // formData = this.store.linkFilter({
 * //   // annotated because filterForm is declared below
 * //   updateWhen: (): boolean => this.filterForm().valid(),
 * // });
 */
// Overload: state key source
export function withLink<
  Input extends SignalStoreFeatureResult,
  K extends keyof Input['state'] & string,
>(
  source: K,
  options?: LinkSourceOptions<Input, K>,
): SignalStoreFeature<
  Input,
  {
    state: {};
    props: {};
    methods: {
      [P in `link${Capitalize<string & K>}`]: LinkMethod<Input['state'][K]>;
    };
  }
>;
// Overload: custom name with computation
export function withLink<
  Input extends SignalStoreFeatureResult,
  T,
  N extends string,
>(
  name: N,
  options: LinkComputedOptions<Input, T>,
): SignalStoreFeature<
  Input,
  {
    state: {};
    props: {};
    methods: {
      [P in `link${Capitalize<string & N>}`]: LinkMethod<T>;
    };
  }
>;

export function withLink<Input extends SignalStoreFeatureResult>(
  name: string,
  options?: LinkSourceOptions<Input, any> | LinkComputedOptions<Input, any>,
): SignalStoreFeature<Input, any> {
  return withFeatureFactory((store) => {
    const computation =
      options && 'computation' in options ? options.computation : undefined;
    const source: () => any = computation
      ? () => computation(store as any)
      : (store as any)[name];

    const equal = options?.equal ?? Object.is;
    const update = options?.update
      ? (value: any) => options.update!(value, store as any)
      : (value: any) => patchState(store as any, { [name]: value });

    // untracked: set/update must never register dependencies when called
    // inside a reactive context, matching WritableSignal semantics — the
    // update itself is wrapped too, since it can read other signals
    // (e.g. filterEntities reads entities())
    const guardedUpdate = (value: any) =>
      untracked(() => {
        if (!equal(value, source())) {
          update(value);
        }
      });

    const linkMethodName = `link${capitalize(name)}`;

    return signalStoreFeature(
      withMethods(() => ({
        [linkMethodName]: (options?: LinkOptions) => {
          const linkOptions = options as
            | (LinkCommonOptions<any> & {
                syncWith?: WritableSignal<any>;
                readFrom?: Signal<any> | ((prev: any) => any);
                writeTo?: WritableSignal<any> | ((value: any) => void);
                initialValue?: 'store' | 'external';
              })
            | undefined;
          const updateWhen = linkOptions?.updateWhen;
          // with updateWhen the linked signal is a buffer over the source:
          // writes stay local until the gate opens. Without it, writes go
          // straight to the store.
          const linked: WritableSignal<any> = updateWhen
            ? linkedSignal(() => source(), { equal })
            : delegatedSignal({
                computation: () => source(),
                update: guardedUpdate,
                equal,
              });

          if (updateWhen) {
            // buffer -> store; updateWhen is called tracked so its own
            // dependencies re-run the effect, flushing a value that was
            // held back while the gate was closed
            effect(() => {
              const value = linked();
              if (updateWhen(value)) {
                untracked(() => guardedUpdate(value));
              }
            });
          }

          const readFrom = linkOptions?.readFrom;
          if (readFrom) {
            // the function form receives the previous linked value untracked,
            // so a merge can not register the store (or buffer) as a
            // dependency — only the external signals it reads re-run it
            const read = isSignal(readFrom)
              ? () => readFrom()
              : () => readFrom(untracked(linked));
            // one way: the store reads the signal, never writes it back
            const initial = untracked(read);
            linked.set(initial);
            // the initial sync above already applied this value, so the effect
            // below must not apply it again — that would discard a buffered
            // write made before the first tick
            let lastRead: unknown = initial;
            effect(() => {
              const value = read();
              if (equal(value, lastRead)) return;
              lastRead = value;
              untracked(() => linked.set(value));
            });
          }

          const writeTo = linkOptions?.writeTo;
          if (writeTo) {
            const write =
              typeof (writeTo as Partial<WritableSignal<any>>).set ===
              'function'
                ? (value: any) => (writeTo as WritableSignal<any>).set(value)
                : (writeTo as (value: any) => void);
            // changes only: the value at link time is not pushed, so an
            // output does not emit spuriously and a readFrom mapping is not
            // echoed straight back. Reads the source, not the buffer, so
            // only values committed to the store are pushed out. The linked
            // signal (not the source) seeds the guard so a readFrom initial
            // value still pending in the updateWhen buffer is not pushed
            // once the gate commits it.
            let lastWritten: unknown = untracked(linked);
            effect(() => {
              const value = source();
              if (equal(value, lastWritten)) return;
              lastWritten = value;
              untracked(() => write(value));
            });
          }

          const syncWith = linkOptions?.syncWith;
          if (syncWith) {
            const initialValue = linkOptions?.initialValue ?? 'external';
            // last value seen coming from the external signal, so writes we
            // made to it ourselves are not mistaken for user edits. Both
            // branches below seed it before the effects run
            let lastExternal: unknown;
            if (initialValue === 'external') {
              linked.set(untracked(syncWith));
              // the initial sync above already applied this value, so the
              // effect below must not apply it again — that would discard a
              // buffered write made before the first tick
              lastExternal = untracked(syncWith);
            } else {
              syncWith.set(untracked(source));
              // our own write: without recording it, the effect below would
              // treat its first run as a user edit and force-apply the
              // external snapshot — reverting a store change or clobbering a
              // buffered write made before the first tick
              lastExternal = untracked(source);
            }
            // external -> linked
            effect(() => {
              const value = syncWith();
              if (equal(value, lastExternal)) return;
              lastExternal = value;
              untracked(() => linked.set(value));
            });
            // store -> external. Reads the source, not the buffer, so an
            // external model() only ever sees values committed to the store.
            effect(() => {
              const value = source();
              untracked(() => {
                if (!equal(syncWith(), value)) {
                  // our own write, not a user edit: recording it keeps the
                  // effect above from pushing it back into the buffer and
                  // overwriting a value the gate is still holding
                  lastExternal = value;
                  syncWith.set(value);
                }
              });
            });
          }
          return linked;
        },
      })),
    );
  }) as any;
}

function delegatedSignal<T>(options: {
  computation: () => T;
  update: (value: T) => void;
  equal?: (a: T, b: T) => boolean;
}): WritableSignal<T> {
  const internalSignal = computed(options.computation, {
    equal: options.equal,
  });

  // reuses the computed's SIGNAL node so isSignal/toSignal interop treats
  // this as a real signal; set/update only exist on the wrapper, so code
  // that writes through the node itself would bypass them
  const res: WritableSignal<T> = Object.assign(() => internalSignal(), {
    [SIGNAL]: internalSignal[SIGNAL],
    set: (value: T) => options.update(value),
    update: (updateFn: (value: T) => T) => {
      const newValue = updateFn(untracked(internalSignal));
      options.update(newValue);
    },
    asReadonly: () => internalSignal,
  } as WritableSignal<T>);
  return res;
}
