import {
  computed,
  effect,
  isSignal,
  isWritableSignal,
  linkedSignal,
  Signal,
  untracked,
  WritableSignal,
} from '@angular/core';
import { SIGNAL } from '@angular/core/primitives/signals';
import {
  patchState,
  SignalStoreFeature,
  signalStoreFeature,
  SignalStoreFeatureResult,
  withMethods,
} from '@ngrx/signals';

import { capitalize } from '../util';
import { withFeatureFactory } from '../with-feature-factory/with-feature-factory';
import { StoreSource } from '../with-feature-factory/with-feature-factory.model';

/** Nothing has been synced from the external signal yet. */
const NOT_SYNCED = Symbol('notSynced');

export type LinkOptions<T = any> = {
  /**
   * Which value wins when an external signal is linked.
   * - 'external' (default): the external signal's current value is pushed to the store.
   * - 'store': the store value is written to the external signal (requires a WritableSignal;
   *   ignored for read-only signals, which are always one-way external → store).
   */
  initialValue?: 'store' | 'external';
  /**
   * Gates which writes reach the store. When provided, the returned signal
   * becomes a `linkedSignal` buffer over the source: writes are kept locally
   * and only pushed to the store when `updateWhen(value)` returns true.
   *
   * It runs inside an effect, so it is reactive: a value held back while it
   * returned false is pushed as soon as its dependencies make it true
   * (e.g. a form becoming valid).
   *
   * Requires an injection context, since an effect is created.
   */
  updateWhen?: (value: T) => boolean;
};

/**
 * The `link<Name>()` method generated by `withLink`. Callable with an external
 * signal to sync, with just the options, or with neither.
 */
export type LinkMethod<T> = {
  (external?: Signal<T>, options?: LinkOptions<T>): WritableSignal<T>;
  (options: LinkOptions<T>): WritableSignal<T>;
};

export type LinkSourceOptions<
  Input extends SignalStoreFeatureResult,
  K extends keyof Input['state'],
> = {
  update?: (
    value: Input['state'][NoInfer<K>],
    store: StoreSource<Input>,
  ) => void;
  /**
   * Equality used to suppress redundant syncs in both directions.
   * Defaults to Object.is. Provide a structural comparison when the source
   * produces fresh object/array references (e.g. entity selections).
   */
  equal?: (
    a: Input['state'][NoInfer<K>],
    b: Input['state'][NoInfer<K>],
  ) => boolean;
  computation?: never;
};

export type LinkComputedOptions<Input extends SignalStoreFeatureResult, T> = {
  computation: (store: StoreSource<Input>) => T;
  update: (value: T, store: StoreSource<Input>) => void;
  /**
   * Equality used to suppress redundant syncs in both directions.
   * Defaults to Object.is. Provide a structural comparison when the source
   * produces fresh object/array references (e.g. entity selections).
   */
  equal?: (a: NoInfer<T>, b: NoInfer<T>) => boolean;
};

/**
 * Generates a `link<Name>()` method that connects store state to component
 * signals (inputs, models, signal forms).
 *
 * The first argument names the generated method and doubles as the state key
 * to link to, unless `computation` is provided in the options — then it is
 * just a name and the value is derived from the store.
 *
 * The method always returns a WritableSignal that is a live view of the store:
 * reading it reads the source, writing it calls `update` (or `patchState` by
 * default). Optionally pass an external signal to keep it in sync with the
 * store as well:
 * - WritableSignal (e.g. `model()`): two-way sync.
 * - Read-only Signal (e.g. `input()`): one-way external → store.
 *
 * It can be called as `link<Name>(external?, options?)` or, when there is no
 * external signal to sync, with the options alone: `link<Name>(options)`.
 *
 * Both sync directions are guarded by `equal` (default `Object.is`), so writes
 * only happen when the value actually changed — this prevents echo loops when
 * `update` transforms the value.
 *
 * Passing an external signal, or the `updateWhen` option, requires an injection
 * context (field initializer or constructor), because effects are created to
 * keep things in sync. The plain no-arg form has no such requirement.
 *
 * @param name - State key to link to, or a custom name when `computation` is used
 * @param options.computation - Derive the linked value from the store
 * @param options.update - How writes reach the store; defaults to
 *   `patchState(store, { [name]: value })`, required with `computation`
 * @param options.equal - Equality guard for both sync directions
 *
 * @example
 * // State key - generates linkFilter(), writes patch state
 * const Store = signalStore(
 *   withState({ filter: { search: '' } }),
 *   withLink('filter'),
 * );
 * // in a component:
 * // filterForm = form(this.store.linkFilter());
 *
 * @example
 * // State key with custom update
 * withLink('productEntitiesFilter', {
 *   update: (value, store) => store.filterProductEntities({ filter: value }),
 * });
 *
 * @example
 * // Custom name with computation + update, synced two-way with a model() input
 * withLink('selectedGenreIds', {
 *   computation: (store) => store.genreIdsSelected(),
 *   update: (value, store) =>
 *     store.selectGenreEntities({ ids: value, clearSelectionBeforeSelect: true }),
 *   equal: (a, b) => a.length === b.length && a.every((v, i) => v === b[i]),
 * });
 * // in a component:
 * // value = model<string[]>([]);
 * // valueField = form(this.store.linkSelectedGenreIds(this.value));
 *
 * @example
 * // Buffered writes: only valid form data reaches the store
 * // filterForm = form(this.formData, (value) => required(value.search));
 * // formData = this.store.linkFilter({
 * //   updateWhen: () => this.filterForm().valid(),
 * // });
 */
// Overload: state key source
export function withLink<
  Input extends SignalStoreFeatureResult,
  K extends keyof Input['state'] & string,
>(
  source: K,
  options?: LinkSourceOptions<Input, K>,
): SignalStoreFeature<
  Input,
  {
    state: {};
    props: {};
    methods: {
      [P in `link${Capitalize<string & K>}`]: LinkMethod<Input['state'][K]>;
    };
  }
>;
// Overload: custom name with computation
export function withLink<
  Input extends SignalStoreFeatureResult,
  T,
  N extends string,
>(
  name: N,
  options: LinkComputedOptions<Input, T>,
): SignalStoreFeature<
  Input,
  {
    state: {};
    props: {};
    methods: {
      [P in `link${Capitalize<string & N>}`]: LinkMethod<T>;
    };
  }
>;

export function withLink<Input extends SignalStoreFeatureResult>(
  name: string,
  options?: LinkSourceOptions<Input, any> | LinkComputedOptions<Input, any>,
): SignalStoreFeature<Input, any> {
  return withFeatureFactory((store) => {
    const computation = options && 'computation' in options
      ? options.computation
      : undefined;
    const source: () => any = computation
      ? () => computation(store as any)
      : (store as any)[name];

    const equal = options?.equal ?? Object.is;
    const update = options?.update
      ? (value: any) => options.update!(value, store as any)
      : (value: any) => patchState(store as any, { [name]: value });

    // untracked: set/update must never register dependencies when called
    // inside a reactive context, matching WritableSignal semantics
    const guardedUpdate = (value: any) => {
      if (!equal(value, untracked(source))) {
        update(value);
      }
    };

    const linkMethodName = `link${capitalize(name)}`;

    return signalStoreFeature(
      withMethods(() => ({
        [linkMethodName]: (
          externalOrOptions?: Signal<any> | LinkOptions,
          optionsArg?: LinkOptions,
        ) => {
          // the external signal is optional, so the options can take its
          // place. An explicit undefined first argument still leaves the
          // options in the second one
          const external = isSignal(externalOrOptions)
            ? (externalOrOptions as Signal<any>)
            : undefined;
          const linkOptions = (optionsArg ??
            (isSignal(externalOrOptions) ? undefined : externalOrOptions)) as
            | LinkOptions
            | undefined;
          const updateWhen = linkOptions?.updateWhen;
          // with updateWhen the linked signal is a buffer over the source:
          // writes stay local until the gate opens. Without it, writes go
          // straight to the store.
          const linked: WritableSignal<any> = updateWhen
            ? linkedSignal(() => source(), { equal })
            : delegatedSignal({
                computation: () => source(),
                update: guardedUpdate,
                equal,
              });

          if (updateWhen) {
            // buffer -> store; updateWhen is called tracked so its own
            // dependencies re-run the effect, flushing a value that was
            // held back while the gate was closed
            effect(() => {
              const value = linked();
              if (updateWhen(value)) {
                untracked(() => guardedUpdate(value));
              }
            });
          }

          if (external) {
            const initialValue = linkOptions?.initialValue ?? 'external';
            // last value seen coming from the external signal, so writes we
            // made to it ourselves are not mistaken for user edits. NOT_SYNCED
            // means nothing has been applied from it yet
            let lastExternal: unknown = NOT_SYNCED;
            if (initialValue === 'external') {
              linked.set(untracked(external));
              // the initial sync above already applied this value, so the
              // effect below must not apply it again — that would discard a
              // buffered write made before the first tick
              lastExternal = untracked(external);
            } else if (isWritableSignal(external)) {
              external.set(untracked(source));
            }
            // external -> linked
            effect(() => {
              const value = external();
              if (lastExternal !== NOT_SYNCED && equal(value, lastExternal))
                return;
              lastExternal = value;
              untracked(() => linked.set(value));
            });
            // store -> external, only when the external signal is writable.
            // Reads the source, not the buffer, so an external model() only
            // ever sees values committed to the store.
            if (isWritableSignal(external)) {
              effect(() => {
                const value = source();
                untracked(() => {
                  if (!equal(external(), value)) {
                    // our own write, not a user edit: recording it keeps the
                    // effect above from pushing it back into the buffer and
                    // overwriting a value the gate is still holding
                    lastExternal = value;
                    external.set(value);
                  }
                });
              });
            }
          }
          return linked;
        },
      })),
    );
  }) as any;
}

function delegatedSignal<T>(options: {
  computation: () => T;
  update: (value: T) => void;
  equal?: (a: T, b: T) => boolean;
}): WritableSignal<T> {
  const internalSignal = computed(options.computation, {
    equal: options.equal,
  });

  // reuses the computed's SIGNAL node so isSignal/toSignal interop treats
  // this as a real signal; set/update only exist on the wrapper, so code
  // that writes through the node itself would bypass them
  const res: WritableSignal<T> = Object.assign(() => internalSignal(), {
    [SIGNAL]: internalSignal[SIGNAL],
    set: (value: T) => options.update(value),
    update: (updateFn: (value: T) => T) => {
      const newValue = updateFn(untracked(internalSignal));
      options.update(newValue);
    },
    asReadonly: () => internalSignal,
  } as WritableSignal<T>);
  return res;
}
