import { EffectRef, Injector } from '@angular/core';
import {
  getState,
  patchState,
  signalMethod,
  SignalStoreFeature,
  signalStoreFeature,
  SignalStoreFeatureResult,
  withMethods,
} from '@ngrx/signals';

import { capitalize } from '../util';

/**
 * Setter generated by `withStateSetter` for a state prop of type T.
 * Accepts a plain value, a signal/reactive fn (keeps state in sync via
 * `signalMethod`), or an updater `(current) => next` for partial updates.
 */
export type StateSetter<T> = ((
  input: T | (() => T) | ((current: T) => T),
  config?: { injector?: Injector },
) => EffectRef) &
  EffectRef;

/**
 * Generates a `set<Prop>()` method for each provided state prop that patches
 * the state with the given value. The generated methods are `signalMethod`s,
 * so they accept either a plain value or a signal/computed; when given a
 * signal, the state is kept in sync with it. They also accept an updater
 * function `(current) => next` receiving the current prop value, for partial
 * updates.
 *
 * Note: updaters are told apart from reactive fns by arity — an updater must
 * declare its parameter (`(current) => ...`), a zero-arg fn is treated as a
 * reactive computation.
 *
 * @param keys - names of state props to generate setters for
 *
 * @example
 * const Store = signalStore(
 *   withState({
 *     a: { b: '' },
 *     c: 1,
 *     d: 12,
 *   }),
 *   withStateSetter('a', 'd'),
 * );
 * // generates the methods
 * store.setA({ b: 'hello' }); // patchState(store, { a: { b: 'hello' } })
 * store.setD(42);             // patchState(store, { d: 42 })
 * // updater fn receives the current prop value, for partial updates:
 * store.setA((a) => ({ ...a, b: 'partial' }));
 * // signalMethod also accepts signals, keeping state in sync:
 * store.setD(this.dInput); // dInput: Signal<number>
 */
export function withStateSetter<
  Input extends SignalStoreFeatureResult,
  K extends keyof Input['state'] & string,
>(
  ...keys: K[]
): SignalStoreFeature<
  Input,
  {
    state: {};
    props: {};
    methods: {
      [P in K as `set${Capitalize<P>}`]: StateSetter<Input['state'][P]>;
    };
  }
>;
export function withStateSetter(
  ...keys: string[]
): SignalStoreFeature<SignalStoreFeatureResult, any> {
  return signalStoreFeature(
    withMethods((store) => {
      const state = getState(store);
      return keys.reduce(
        (methods, key) => {
          if (!(key in state)) {
            console.warn(
              `@ngrx-traits/signals: withStateSetter('${key}') does not match any state prop`,
            );
          }
          const setValue = signalMethod<unknown>((value) =>
            patchState(store, { [key]: value }),
          );
          // updaters take the current value as param; signalMethod treats any
          // fn as a zero-arg reactive computation, so route by arity
          const setter = (
            value: unknown,
            config?: { injector?: Injector },
          ): EffectRef => {
            if (typeof value === 'function' && value.length > 0) {
              patchState(store, (state: Record<string, unknown>) => ({
                [key]: value(state[key]),
              }));
              return { destroy: () => void 0 };
            }
            return setValue(value, config);
          };
          setter.destroy = setValue.destroy;
          methods[`set${capitalize(key)}`] = setter;
          return methods;
        },
        {} as Record<string, StateSetter<unknown>>,
      );
    }),
  ) as SignalStoreFeature<SignalStoreFeatureResult, any>;
}
