import { EffectRef, Injector } from '@angular/core';
import {
  getState,
  patchState,
  signalMethod,
  SignalStoreFeature,
  signalStoreFeature,
  SignalStoreFeatureResult,
  withMethods,
} from '@ngrx/signals';

import { capitalize } from '../util';

/**
 * Setter generated by `withStateSetter` for a state prop of type T.
 * Accepts a plain value, a signal/reactive fn (keeps state in sync via
 * `signalMethod`), or an updater `(current) => next` for partial updates.
 */
export type StateSetter<T> = ((
  input: T | (() => T) | ((current: T) => T),
  config?: { injector?: Injector },
) => EffectRef) &
  EffectRef;

/** Prop name without its leading underscore, if it has one. */
type Unprefixed<P extends string> = P extends `_${infer R}` ? R : P;

/**
 * Name of the setter generated by `withStateSetter` for state prop P: always
 * the public `set<P>`, a leading underscore in the prop name is dropped
 * (`_filter` -> `setFilter`).
 */
export type SetterKey<P extends string> = `set${Capitalize<Unprefixed<P>>}`;

/**
 * Name of the setter generated by `withStatePrivateSetter` for state prop P:
 * always the private `_set<P>`, regardless of whether P itself starts with an
 * underscore (`filter` and `_filter` both -> `_setFilter`).
 */
export type PrivateSetterKey<P extends string> =
  `_set${Capitalize<Unprefixed<P>>}`;

function setterKey(key: string, isPrivate: boolean): string {
  const prop = capitalize(key.startsWith('_') ? key.slice(1) : key);
  return isPrivate ? `_set${prop}` : `set${prop}`;
}

function stateSetterFactory(
  keys: string[],
  { featureName, isPrivate }: { featureName: string; isPrivate: boolean },
): SignalStoreFeature<SignalStoreFeatureResult, any> {
  return signalStoreFeature(
    withMethods((store) => {
      const state = getState(store);
      return keys.reduce(
        (methods, key) => {
          if (!(key in state)) {
            console.warn(
              `@ngrx-traits/signals: ${featureName}('${key}') does not match any state prop`,
            );
          }
          const setValue = signalMethod<unknown>((value) =>
            patchState(store, { [key]: value }),
          );
          // updaters take the current value as param; signalMethod treats any
          // fn as a zero-arg reactive computation, so route by arity
          const setter = (
            value: unknown,
            config?: { injector?: Injector },
          ): EffectRef => {
            if (typeof value === 'function' && value.length > 0) {
              patchState(store, (state: Record<string, unknown>) => ({
                [key]: value(state[key]),
              }));
              return { destroy: () => void 0 };
            }
            return setValue(value, config);
          };
          setter.destroy = setValue.destroy;
          methods[setterKey(key, isPrivate)] = setter;
          return methods;
        },
        {} as Record<string, StateSetter<unknown>>,
      );
    }),
  ) as SignalStoreFeature<SignalStoreFeatureResult, any>;
}

/**
 * Generates a `set<Prop>()` method for each provided state prop that patches
 * the state with the given value. The generated methods are `signalMethod`s,
 * so they accept either a plain value or a signal/computed; when given a
 * signal, the state is kept in sync with it. They also accept an updater
 * function `(current) => next` receiving the current prop value, for partial
 * updates.
 *
 * The generated setters are always public: a leading underscore in the prop
 * name is dropped (`_filter` -> `setFilter`). Use `withStatePrivateSetter` to
 * generate setters only accessible inside the store.
 *
 * Note: updaters are told apart from reactive fns by arity — an updater must
 * declare its parameter (`(current) => ...`), a zero-arg fn is treated as a
 * reactive computation.
 *
 * @param keys - names of state props to generate setters for
 *
 * @example
 * const Store = signalStore(
 *   withState({
 *     a: { b: '' },
 *     c: 1,
 *     d: 12,
 *   }),
 *   withStateSetter('a', 'd'),
 * );
 * // generates the methods
 * store.setA({ b: 'hello' }); // patchState(store, { a: { b: 'hello' } })
 * store.setD(42);             // patchState(store, { d: 42 })
 * // updater fn receives the current prop value, for partial updates:
 * store.setA((a) => ({ ...a, b: 'partial' }));
 * // signalMethod also accepts signals, keeping state in sync:
 * store.setD(this.dInput); // dInput: Signal<number>
 */
export function withStateSetter<
  Input extends SignalStoreFeatureResult,
  K extends keyof Input['state'] & string,
>(
  ...keys: K[]
): SignalStoreFeature<
  Input,
  {
    state: {};
    props: {};
    methods: {
      [P in K as SetterKey<P>]: StateSetter<Input['state'][P]>;
    };
  }
>;
export function withStateSetter(
  ...keys: string[]
): SignalStoreFeature<SignalStoreFeatureResult, any> {
  return stateSetterFactory(keys, {
    featureName: 'withStateSetter',
    isPrivate: false,
  });
}

/**
 * Like `withStateSetter`, but the generated setters are private: for each
 * provided state prop it generates a `_set<Prop>()` method, which starts with
 * an underscore, making it only accessible inside the store. Useful to allow a
 * prop to be publicly readable while only writable from within the store.
 *
 * The generated methods behave exactly like the ones from `withStateSetter`:
 * they are `signalMethod`s that accept a plain value, a signal/computed (keeps
 * state in sync), or an updater function `(current) => next` for partial
 * updates. A leading underscore in the prop name is dropped, so `filter` and
 * `_filter` both generate `_setFilter`.
 *
 * @param keys - names of state props to generate private setters for
 *
 * @example
 * const Store = signalStore(
 *   withState({
 *     filter: '',
 *     d: 12,
 *   }),
 *   withStatePrivateSetter('filter'),
 *   withMethods((store) => ({
 *     clearFilter: () => store._setFilter(''), // usable inside the store
 *   })),
 * );
 * // outside the store, filter is readable but _setFilter is not accessible
 * store.filter();
 */
export function withStatePrivateSetter<
  Input extends SignalStoreFeatureResult,
  K extends keyof Input['state'] & string,
>(
  ...keys: K[]
): SignalStoreFeature<
  Input,
  {
    state: {};
    props: {};
    methods: {
      [P in K as PrivateSetterKey<P>]: StateSetter<Input['state'][P]>;
    };
  }
>;
export function withStatePrivateSetter(
  ...keys: string[]
): SignalStoreFeature<SignalStoreFeatureResult, any> {
  return stateSetterFactory(keys, {
    featureName: 'withStatePrivateSetter',
    isPrivate: true,
  });
}
