import { createMultiSelectionTraitActions } from './multi-selection.trait.actions';
import { SortActions, SortKeyedConfig } from '../sort';
import { createMultiSelectionTraitSelectors } from './multi-selection.trait.selectors';
import {
  MultipleSelectionSelectors,
  MultiSelectActions,
} from './multi-selection.model';
import {
  PaginationActions,
  PaginationKeyedConfig,
} from '../pagination/pagination.model';
import {
  LoadEntitiesActions,
  LoadEntitiesKeyedConfig,
  LoadEntitiesSelectors,
  loadEntitiesTraitKey,
} from '../load-entities/load-entities.model';
import { createTraitFactory } from 'ngrx-traits';
import { CrudActions } from '../crud/crud.model';
import {
  createMultiSelectionInitialState,
  createMultiSelectionTraitReducer,
} from './multi-selection.trait.reducer';
import { createMultiSelectionTraitMutators } from './multi-selection.trait.mutators';
import { FilterActions } from '../filter';
import {
  TraitActionsFactoryConfig,
  TraitInitialStateFactoryConfig,
  TraitSelectorsFactoryConfig,
  TraitStateMutatorsFactoryConfig,
} from 'ngrx-traits';

/**
 * Generates ngrx code to add multi selection to a list
 *
 * @example
 * // The following trait config
 *
 * export interface TestState
 * extends EntityAndStatusState<Todo>,MultipleSelectionState{}
 *
 *    const traits = createEntityFeatureFactory(
 *      addLoadEntities<Todo>(),
 *      addMultiSelection<Todo>()
 *    )({
 *      actionsGroupKey: '[Todos]',
 *      featureSelector: createFeatureSelector<TestState>>(
 *        'todos',
 *      ),
 *    });
 * // will generate  the following actions and selectors, plus the ones generated by other traits
 * traits.actions.multiSelect({id})
 * traits.actions.multiDeselect({id})
 * traits.actions.multiToggleSelect({id})
 * traits.actions.toggleSelectAll()
 * traits.actions.multiClearSelection()
 *
 * traits.selectors.selectIdSelected()
 * traits.selectors.selectEntitySelected()
 */
export function addMultiSelection<Entity>() {
  return createTraitFactory({
    key: 'multiSelection',
    depends: [loadEntitiesTraitKey],
    actions: ({ actionsGroupKey }: TraitActionsFactoryConfig) =>
      createMultiSelectionTraitActions(actionsGroupKey),
    selectors: ({ previousSelectors }: TraitSelectorsFactoryConfig) =>
      createMultiSelectionTraitSelectors<Entity>(
        previousSelectors as LoadEntitiesSelectors<Entity>
      ),
    initialState: ({ previousInitialState }: TraitInitialStateFactoryConfig) =>
      createMultiSelectionInitialState<Entity>(previousInitialState),
    mutators: ({ allSelectors }: TraitStateMutatorsFactoryConfig) =>
      createMultiSelectionTraitMutators<Entity>(
        allSelectors as MultipleSelectionSelectors<Entity>
      ),
    reducer: ({ initialState, allActions, allMutators, allConfigs }) =>
      createMultiSelectionTraitReducer(
        initialState,
        allActions as MultiSelectActions &
          CrudActions<Entity> &
          SortActions<Entity> &
          LoadEntitiesActions<Entity> &
          FilterActions<any> &
          PaginationActions,
        allMutators,
        allConfigs as LoadEntitiesKeyedConfig<Entity> &
          PaginationKeyedConfig &
          SortKeyedConfig<Entity>
      ),
  });
}
