import {
  createTraitFactory,
  TraitActionsFactoryConfig,
  TraitInitialStateFactoryConfig,
} from 'ngrx-traits';

import { createSingleSelectionTraitActions } from './single-selection.trait.actions';
import { createSingleSelectionTraitSelectors } from './single-selection.trait.selectors';
import {
  createSingleSelectionInitialState,
  createSingleSelectionTraitReducer,
} from './single-selection.trait.reducer';
import { createSingleSelectionTraitMutators } from './single-selection.trait.mutators';
import {
  LoadEntitiesActions,
  LoadEntitiesKeyedConfig,
  loadEntitiesTraitKey,
} from '../load-entities/load-entities.model';
import {
  SortEntitiesActions,
  SortEntitiesKeyedConfig,
} from '../sort/sort.model';
import {
  SelectEntityActions,
  SelectEntityConfig,
  SelectEntityKeyedConfig,
} from './single-selection.model';
import { CrudEntitiesActions } from '../crud/crud.model';
import {
  EntitiesPaginationActions,
  EntitiesPaginationKeyedConfig,
} from '../pagination/pagination.model';
import { FilterEntitiesActions } from '../filter';

/**
 * Generates ngrx code to add single selection to a list
 * @param config
 * @param config.selectedId - Default selected id
 *
 * @example
 * // The following trait config
 *
 * export interface TestState
 * extends EntityAndStatusState<Todo>,SingleSelectionState{}
 *
 *    const traits = createEntityFeatureFactory(
 *      addLoadEntities<Todo>(),
 *      addSelectEntity<Todo>()
 *    )({
 *      actionsGroupKey: '[Todos]',
 *      featureSelector: createFeatureSelector<TestState>>(
 *        'todos',
 *      ),
 *    });
 * // will generate  the following actions and selectors, plus the ones generated by other traits
 * traits.actions.select({id})
 * traits.actions.deselect()
 * traits.actions.toggleSelect({id})
 * traits.selectors.selectIdSelected()
 * traits.selectors.selectEntitySelected()
 */
export function addSelectEntity<Entity>(config?: SelectEntityConfig) {
  return createTraitFactory({
    key: 'singleSelection',
    depends: [loadEntitiesTraitKey],
    config,
    actions: ({ actionsGroupKey }: TraitActionsFactoryConfig) =>
      createSingleSelectionTraitActions(actionsGroupKey),
    selectors: () => createSingleSelectionTraitSelectors<Entity>(),
    mutators: () => createSingleSelectionTraitMutators(),
    initialState: ({
      previousInitialState,
      allConfigs,
    }: TraitInitialStateFactoryConfig) =>
      createSingleSelectionInitialState<Entity>(
        previousInitialState,
        allConfigs as SelectEntityKeyedConfig
      ),
    reducer: ({ initialState, allActions, allMutators, allConfigs }) =>
      createSingleSelectionTraitReducer(
        initialState,
        allActions as SelectEntityActions &
          CrudEntitiesActions<Entity> &
          SortEntitiesActions<Entity> &
          EntitiesPaginationActions &
          FilterEntitiesActions<any> &
          LoadEntitiesActions<Entity>,
        allMutators,
        allConfigs as SelectEntityKeyedConfig &
          LoadEntitiesKeyedConfig<Entity> &
          EntitiesPaginationKeyedConfig &
          SortEntitiesKeyedConfig<Entity>
      ),
  });
}
