import { SignalStoreFeatureResult } from '@ngrx/signals';
import {
  EntityProps,
  EntityState,
  NamedEntityProps,
  NamedEntityState,
} from '@ngrx/signals/entities';

import {
  CallStatusComputed,
  CallStatusMethods,
  CallStatusState,
  NamedCallStatusComputed,
  NamedCallStatusMethods,
  NamedCallStatusState,
} from './with-call-status/with-call-status.model';

/**
 * Types in this file replace the giant structural mismatch typescript reports
 * when a store feature is used without the features it depends on, with a
 * readable message like:
 *
 * Property 'Missing store feature: withEntitiesLoadingCall requires
 * withCallStatus({ collection: 'product' }) to be present in the store before
 * it' is missing in type ...
 *
 * They check if the required feature keys are already in the Input, if they
 * are, the real requirement is returned, so the store is type checked as
 * before, if they are not, a feature result with a single method named after
 * the error message is returned, that method can never exist in the store, so
 * typescript reports it as missing and shows the message.
 */

/**
 * A feature result that can never be satisfied, its only member is named after
 * the error message, so typescript shows the message to the user.
 */
export type MissingFeatureError<Message extends string> = {
  state: {};
  props: {};
  methods: {
    [K in `Missing store feature: ${Message}`]: () => void;
  } & {
    // if Message is not a literal, the mapped type above becomes an index
    // signature, which {} satisfies, this key keeps the error in that case
    __missingStoreFeature: () => void;
  };
};

/**
 * True when Input['state'] is the SignalStoreFeatureResult constraint instead of
 * a real store state, which happens when the feature is used inside another
 * generic feature, e.g. inside withFeatureFactory, there the store is only known
 * at the point the outer feature is added, so there is nothing to check yet.
 */
type IsOpaqueState<State> = object extends State
  ? string extends State
    ? false
    : true
  : false;

/**
 * Returns the Requirement if the store already has the state Key generated by
 * the required feature, or an error message naming the missing feature.
 */
export type RequireFeature<
  Input extends SignalStoreFeatureResult,
  Key extends string,
  Requirement extends SignalStoreFeatureResult,
  Message extends string,
> =
  IsOpaqueState<Input['state']> extends true
    ? Requirement
    : [Key] extends [keyof Input['state']]
      ? Requirement
      : MissingFeatureError<Message>;

/**
 * How the required feature config looks in the error message, e.g.
 * withEntities({ entity, collection: 'product' })
 */
type EntitiesConfig<Collection extends string> = Collection extends ''
  ? '{ entity }'
  : `{ entity, collection: '${Collection}' }`;

type CollectionConfig<Collection extends string> = Collection extends ''
  ? ''
  : `{ collection: '${Collection}' }`;

/**
 * The state, props and methods withEntities generates for a collection.
 */
export type EntitiesRequirement<
  Entity,
  Collection extends string,
> = Collection extends ''
  ? { state: EntityState<Entity>; props: EntityProps<Entity>; methods: {} }
  : {
      state: NamedEntityState<Entity, Collection>;
      props: NamedEntityProps<Entity, Collection>;
      methods: {};
    };

/**
 * The state, props and methods withCallStatus generates for a collection.
 */
export type EntitiesCallStatusRequirement<
  Collection extends string,
  Error = any,
> = Collection extends ''
  ? {
      state: CallStatusState;
      props: CallStatusComputed<Error>;
      methods: CallStatusMethods<Error>;
    }
  : {
      state: NamedCallStatusState<`${Collection}Entities`>;
      props: NamedCallStatusComputed<`${Collection}Entities`, Error>;
      methods: NamedCallStatusMethods<`${Collection}Entities`, Error>;
    };

/**
 * Requires withEntities for the given collection to be present in the store,
 * or fails with a readable error message.
 */
export type RequireEntities<
  Input extends SignalStoreFeatureResult,
  Entity,
  Collection extends string,
  Feature extends string,
  Requirement extends SignalStoreFeatureResult = EntitiesRequirement<
    Entity,
    Collection
  >,
> = RequireFeature<
  Input,
  Collection extends '' ? 'entityMap' : `${Collection}EntityMap`,
  Requirement,
  `${Feature} requires withEntities(${EntitiesConfig<Collection>}) to be present in the store before it`
>;

/**
 * Requires withCallStatus for the given collection to be present in the store,
 * or fails with a readable error message.
 */
export type RequireEntitiesCallStatus<
  Input extends SignalStoreFeatureResult,
  Collection extends string,
  Feature extends string,
  Requirement extends
    SignalStoreFeatureResult = EntitiesCallStatusRequirement<Collection>,
> = RequireFeature<
  Input,
  // withCallStatus declares this key as `${Collection}EntitiesCallStatus`, note
  // getWithCallStatusKeys generates `${Collection}CallStatus` at runtime, if
  // that mismatch is ever fixed this key has to be updated with it
  Collection extends '' ? 'callStatus' : `${Collection}EntitiesCallStatus`,
  Requirement,
  `${Feature} requires withCallStatus(${CollectionConfig<Collection>}) to be present in the store before it`
>;

/**
 * Requires one of the withEntities*Filter features for the given collection to
 * be present in the store, or fails with a readable error message.
 */
export type RequireEntitiesFilter<
  Input extends SignalStoreFeatureResult,
  Collection extends string,
  Feature extends string,
  Requirement extends SignalStoreFeatureResult,
> = RequireFeature<
  Input,
  Collection extends '' ? 'entitiesFilter' : `${Collection}EntitiesFilter`,
  Requirement,
  `${Feature} requires withEntitiesLocalFilter, withEntitiesRemoteFilter or withEntitiesHybridFilter(${EntitiesConfig<Collection>}) to be present in the store before it`
>;

/**
 * Requires one of the withEntities*Sort features for the given collection to be
 * present in the store, or fails with a readable error message.
 */
export type RequireEntitiesSort<
  Input extends SignalStoreFeatureResult,
  Collection extends string,
  Feature extends string,
  Requirement extends SignalStoreFeatureResult,
> = RequireFeature<
  Input,
  Collection extends '' ? 'entitiesSort' : `${Collection}EntitiesSort`,
  Requirement,
  `${Feature} requires withEntitiesLocalSort or withEntitiesRemoteSort(${EntitiesConfig<Collection>}) to be present in the store before it`
>;

/**
 * Requires withEntitiesSingleSelection for the given collection to be present
 * in the store, or fails with a readable error message.
 */
export type RequireEntitiesSingleSelection<
  Input extends SignalStoreFeatureResult,
  Collection extends string,
  Feature extends string,
  Requirement extends SignalStoreFeatureResult,
> = RequireFeature<
  Input,
  Collection extends '' ? 'idSelected' : `${Collection}IdSelected`,
  Requirement,
  `${Feature} requires withEntitiesSingleSelection(${EntitiesConfig<Collection>}) to be present in the store before it`
>;

/**
 * Requires withEntitiesMultiSelection for the given collection to be present in
 * the store, or fails with a readable error message.
 */
export type RequireEntitiesMultiSelection<
  Input extends SignalStoreFeatureResult,
  Collection extends string,
  Feature extends string,
  Requirement extends SignalStoreFeatureResult,
> = RequireFeature<
  Input,
  Collection extends '' ? 'idsSelectedMap' : `${Collection}IdsSelectedMap`,
  Requirement,
  `${Feature} requires withEntitiesMultiSelection(${EntitiesConfig<Collection>}) to be present in the store before it`
>;
